[build]
  command = "echo 'Processing CMS templates...' && exit 0"
  publish = "."

[[plugins]]
  package = "netlify-plugin-cms"
  enabled = true

[context.production.environment]
  NETLIFY_CMS_PREVIEW_STYLES = "true"
  NETLIFY_CMS_BACKEND = "git-gateway"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

[[redirects]]
  from = "/img/*"
  to = "/static/img/:splat"
  status = 200
  force = true
