backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "services"
    label: "Services"
    folder: "_data/services"
    fields:
      - { name: "title", label: "Service", widget: "string" }
      - { name: "price", label: "Price", widget: "string" }
