backend:
  name: github
  repo: carlvddecken/The-Stringer
  branch: main
  auth_scope: repo
  base_url: https://api.netlify.com
  auth_endpoint: oauth2/authorize
  app_id: Ov23li3DZuF3lYFcFiUW

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "home"
    label: "Homepage Content"
    files:
      - label: "Services & Products"
        name: "services"
        file: "content/home.md"
        fields:
          - { name: "services", label: "Services", widget: "list" }
          - { name: "products", label: "Products", widget: "list" }
          - { name: "gallery", label: "Gallery Image URLs", widget: "list" }
          - { name: "contact", label: "Contact Info", widget: "markdown" }

