backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        fields:
          - { name: "services", label: "Services", widget: "markdown",
              default: "<ul><li>Squash racquet restringing – from R220</li><li>Tennis racquet restringing – from R250</li></ul>" }
          - { name: "products", label: "Products", widget: "markdown",
              default: "<ul><li><img src='/img/uploads/squash-racquet.jpg' width='100'> New squash racquets – from R950</li></ul>" }
          - { name: "gallery", label: "Gallery Images", widget: "list",
              field: { name: "image", label: "Image", widget: "image" } }
