backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"  # ← Collection name
    label: "Pages"  # ← UI Label
    files:
      - name: "home"  # ← Required unique name
        file: "index.html"
        label: "Home Page"  # ← Human-readable label
        fields:
          - { name: "services", label: "Services", widget: "markdown" }
          - { name: "products", label: "Products", widget: "markdown" }
