backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        fields:
          - { name: "services", label: "Services", widget: "markdown",
              default: "<ul><li>Squash restringing – R220</li><li>Tennis restringing – R250</li></ul>" }
          - { name: "products", label: "Products", widget: "markdown",
              default: "<ul><li>New squash racquets – R950</li></ul>" }
